[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/","@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]

[invariant]
runs = 128
depth = 128
fail_on_revert = true

#false: it does a lot of runs independent from each other
#true: it runs different parameters until one of the fails, then it crashes the test

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
